#!/usr/bin/env python3
"""
Lab Export
Exports Synthetic Beacons and Real Hashes in STIX 2.1 format.
"""

import json
import time
import os
import sqlite3
import uuid
import config
from evolution import EvolutionLab
from db_manager import DatabaseManager

class StixGenerator:
    def create_indicator(self, hash_value, name, description):
        """Creates a simplified STIX 2.1 Indicator object."""
        return {
            "type": "indicator",
            "id": f"indicator--{uuid.uuid4()}",
            "created": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "modified": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "name": name,
            "description": description,
            "pattern": f"[file:hashes.'SHA-256' = '{hash_value}']",
            "pattern_type": "stix",
            "valid_from": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        }

class HashReplayEngine:
    def __init__(self):
        self.db = DatabaseManager()
        self.export_file = "stix_real_hashes.json"
        self.stix = StixGenerator()

    def generate_artifacts(self):
        conn = sqlite3.connect(config.DB_PATH)
        cursor = conn.cursor()
        cursor.execute("SELECT ioc, source FROM threat_intel WHERE length(ioc)=64 AND ioc GLOB '[0-9a-f]*' LIMIT 500")
        rows = cursor.fetchall()
        conn.close()

        bundle = {
            "type": "bundle",
            "id": f"bundle--{uuid.uuid4()}",
            "objects": []
        }

        for ioc, source in rows:
            indicator = self.stix.create_indicator(
                ioc,
                f"Malware Hash from {source}",
                "Real-world malware hash replayed for simulation."
            )
            bundle["objects"].append(indicator)

        with open(self.export_file, "w") as f:
            json.dump(bundle, f, indent=4)
        print(f"[HashReplay] Exported {len(rows)} STIX objects to {self.export_file}")

class FeedExporter:
    def __init__(self):
        self.lab = EvolutionLab()
        self.export_file = "stix_synthetic_beacons.json"
        self.stix = StixGenerator()

    def generate_and_publish(self):
        hashes = self.lab.evolve()
        unique = list(set(hashes))

        bundle = {
            "type": "bundle",
            "id": f"bundle--{uuid.uuid4()}",
            "objects": []
        }

        for h in unique:
            indicator = self.stix.create_indicator(
                h,
                "Synthetic Beacon Variant",
                "Polymorphic beacon generated by Evolution Lab."
            )
            bundle["objects"].append(indicator)

        with open(self.export_file, "w") as f:
            json.dump(bundle, f, indent=4)
        print(f"[FeedExporter] Exported {len(unique)} STIX objects to {self.export_file}")

if __name__ == "__main__":
    pass
